[package]
edition.workspace = true
license.workspace = true
name = "fish-tempfile"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
nix = { workspace = true, features = ["fs", "feature"] }
rand.workspace = true

[lints]
workspace = true
