[package]
edition.workspace = true
license.workspace = true
name = "fish-build-man-pages"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[build-dependencies]
fish-build-helper.workspace = true
rsconf.workspace = true

[lints]
workspace = true
