[package]
edition.workspace = true
license.workspace = true
name = "fish-build-helper"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
rsconf.workspace = true

[lints]
workspace = true
