[package]
edition.workspace = true
license.workspace = true
name = "fish-color"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
fish-common.workspace = true
fish-widestring.workspace = true

[lints]
workspace = true
