[package]
edition.workspace = true
license.workspace = true
name = "fish-gettext"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
fish-gettext-maps.workspace = true
phf.workspace = true

[lints]
workspace = true
