[package]
edition.workspace = true
license.workspace = true
name = "fish-widestring"
repository.workspace = true
rust-version.workspace = true
version = "0.0.0"

[dependencies]
widestring.workspace = true

[lints]
workspace = true
